/*
Copyright (c) 2015-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Tools for manual memory management
 *
 * New/Delete for classes, structs and arrays. It utilizes dlib.memory
 * for actual memory allocation, so it is possible to switch allocator that is
 * being used. By default, dlib.memory.mallocator.Mallocator is used.
 *
 * Module includes a simple memory profiler that can be turned on with enableMemoryProfiler
 * function. If active, it will store information about every allocation (type and size),
 * and will mark those which are leaked (haven't been deleted).
 *
 * Copyright: Timur Gafarov 2015-2026.
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module dlib.core.memory;

public import rtld.core.memory;
import rtld.memory;

// dlib 1.x compatibility
alias globalAllocator = rtld.memory.defaultAllocator;
alias enableMemoryProfiler = rtld.core.memory.memoryProfilerEnabled;
